### ISSUE TITLE
漫游BT永久关闭

### ISSUE THREAD

**Issue by wenketel** [greensea/rssindexer#1]
天下没有不散的宴席
http://share.popgo.org/

**Comment by greensea** [comment]
OMG
看来要抽空换个抓取源了

**Comment by wenketel** [comment]
现在还在的原创bt站点也只有动漫花园还有[华盟](https://camoe.org/index.php)了吧 ╮（﹀＿﹀）╭

**Comment by holmes8600** [comment]
动漫花园刚刚下载东西过来  暂时还可以用哦   然后还有一个http://www.comicat.org/ 漫猫

**Comment by warsk29** [comment]
花园大陆首页可以上，但是打不开子页面下载种子，大陆的IP被封了，只有VPN可以上。

**Comment by wenketel** [comment]
[**@holmes8600**](https://github.com/holmes8600) commented on [2015年12月25日 GMT+8 上午4:18](https://github.com/greensea/rssindexer/issues/1#issuecomment-167155650):

> 动漫花园刚刚下载东西过来  暂时还可以用哦   然后还有一个[http://www.comicat.org/](http://www.comicat.org/) 漫猫

这个应该是爬花园的内容，这类网站挺多的。

```
http://www.miobt.com/
http://www.kisssub.org/
http://www.comicat.org/
http://www.xkdmbt.com/ 
http://www.acgsou.com/
http://bt.skyts.net/
http://www.36dm.com/
http://share.xfsub.com:88/
```

**Comment by greensea** [comment]
动漫花园把大陆 IP 屏蔽了，这会造成大陆群众下载困难，字幕组可能不会继续在动漫花园发布面向大陆的资源。
不过正如 @wenketel 所说，类似的网站千千万，字幕组会自发地选择一个网站继续发布资源，过不了多久另一个动漫花园就会从这些网站中诞生。
现在这是时间段也挺巧的，十月新番基本完结，一月新番也还没出，估计到一月新番大面积开播的时候，这些网站中就会自己长出一个动漫花园来。

当然如果动漫花园封 IP 只是为了避风头的话，上面的话就当我没说。

所以我现在也在观察情况，看看接下来要从哪家爬资源比较好。

不过意外发现，kisssub 的 RSS 支持关键词搜索，各位有需求的话可以先转战那边。

**Comment by holmes8600** [comment]
@greensea  是的 kisssub确实RSS支持搜索，可惜用RSSowl批量下载还是大有问题。目前为止能真正正常批量下载的，只有曾经的极影和你现在做的这个站。曾经的极影我已不报希望，大大的网站希望以后还是做起来哈，真的是非常非常实用。 我会经常关注最新状况的。 另外不知道现在这个程序更改采集源工程是否比较大，他们死一个我们改一次源不知道靠谱不靠谱。连极影人人都能死，我再不期望他们这些网站能存活多久。感觉以后每次改源，都要抱着分分钟需要再次改源的觉悟。

**Comment by greensea** [comment]
意外发现漫游只是把网页干掉了，RSS 页面还在更新，种子发布页面也依旧正常运转，字幕组也一直在更新资源，不知意欲如何

**Comment by wenketel** [comment]
我就说怎么站点还在更新，不过28号也只更新了4个资源，

```
[The ARC-V Project][遊戲王!ARC-V][Yu-Gi-Oh! ARC-V][087][BIG5][720p][MP4] (人員招募)  
[澄空学园&华盟字幕社] 终结的炽天使 第24话 简 MP4 720p 完     
[The ARC-V Project][游戏王!ARC-V][Yu-Gi-Oh! ARC-V][087][GB][720p][MP4] (人员招募)    
[澄空学园] THE IDOLM@STER MEMORIES OF IDOL WORLD!! 偶像大师10周年纪念特别节目 简体 MP4 720p
```

miobt（kisssub）更新了5个

```
【盲點字幕组】★10月新番[野良神 第二季][Noragami Aragoto][01-13][繁體BIG5][720p][MP4]（人員招募）
【盲點字幕组】★10月新番[野良神 第二季][Noragami Aragoto][13][Fin][繁體BIG5][720p][MP4]（人員招募）
[The ARC-V Project][遊戲王!ARC-V][Yu-Gi-Oh! ARC-V][087][BIG5][720p][MP4] (人員招募) [主页]     
[The ARC-V Project][游戏王!ARC-V][Yu-Gi-Oh! ARC-V][087][GB][720p][MP4] (人员招募) [主页] 
[繁星字幕组][Array Stars][全部成为F ][11][720P][GB&BIG5][简繁中日双语]
```

[华盟](https://camoe.org/index.php?sort=1)更新了⑨个资源。
[花园](https://share.dmhy.org/)更新的最多，数不过来了。
不如改成用花园的源吧。
ps：测试了一下，花园随便用国外http代理也是可以上的。

**Comment by holmes8600** [comment]
希望早日恢复KOTOMI RSS  就资源来说应该还是动漫花园最强

**Comment by greensea** [comment]
好，这几天我就抽空把花园的源给加上

**Comment by greensea** [comment]
添加动漫花园作为新的 RSS 源啦，撒花！_★,°_:.☆(￣▽￣)/$:_.°★_ 。

**Comment by wenketel** [comment]
(๑＞ڡ＜)☆棒

**Comment by holmes8600** [comment]
请教现在资源好像不太同步，掉了好多个
