### ISSUE TITLE
使用RSSowl附件批量下载功能，提示 无法为magnet找到协议处理程序

### ISSUE THREAD

**Issue by holmes8600** [greensea/rssindexer#2]
请教有没有什么解决方案哈 小白一个不懂  求指教

**Comment by greensea** [comment]
问题在于花园只提供了 magnet 链接，而没有提供 BT 种子，所以从花园抓到的资源只有 magnet 链接而没有种子，但 RSSowl 需要下载种子文件，于是就报这个错误了。
解决方案有二：
1. 增加更多的提供种子链接的 RSS 源。但问题是其他站点的资源可能都没有动漫花园的多
2. 根据 magnet 链接创建种子文件。这样做的问题是无法在种子文件中包含文件信息，而且我也不知道这个方案是否可行

我先尽快提供一个过滤功能，可以在搜索结果中只显示来自漫游或花园的资源

**Comment by holmes8600** [comment]
@greensea  动漫花园，每个资源都有一个 會員專用連接:  这个就是bt种子的链接 我刚测试了可以直接下载。   看下有没有帮助。

**Comment by greensea** [comment]
@holmes8600 元旦刚刚旅游回来
多谢提醒，我找到这个链接了，真是起了个怪了，我在抓花园的资源的时候竟然没看到这个种子下载链接
预计今明两天就能提供花园资源的种子下载功能

**Comment by holmes8600** [comment]
@greensea  感动中 (ಥ _ ಥ) 你要是女生我就嫁给你了！

**Comment by greensea** [comment]
来自动漫花园的资源已经可以下载种子啦~~o(_￣▽￣_)ブ
