### ISSUE TITLE
下载种子附件的seed.php 报错了

### ISSUE THREAD

**Issue by whitecodes** [greensea/rssindexer#6]
rss 订阅是正常的，但是附件的 seed.php 不管是浏览器访问还是aria2c下载都报错

浏览器访问有如下的报错信息

Warning: mkdir(): File exists in /home/s/rssindexer/func.php on line 86

Warning: file_put_contents(/home/s/rssindexer/torrent/bf/55/bf55dc318806e7171eee4aac2d608510bba10149.torrent): failed to open stream: Transport endpoint is not connected in /home/s/rssindexer/func.php on line 97

Notice: Undefined variable: url in /home/s/rssindexer/seed.php on line 67

Notice: Undefined variable: ch in /home/s/rssindexer/seed.php on line 67

Warning: curl_error() expects parameter 1 to be resource, null given in /home/s/rssindexer/seed.php on line 67
500 Internal Error

**Comment by greensea** [comment]
服务器的磁盘阵列损坏了，正在抢救中，预计两三天左右可以恢复

**Comment by whitecodes** [comment]
现在还是一样的现象……其他原因？

**Comment by greensea** [comment]
@whitecodes 已修复，原因是磁盘阵列修复之后，没有重新挂载远程文件系统，导致无法访问种子文件

**Comment by greensea** [comment]
今天会更换一下磁盘阵列服务器的系统盘，还会暂停服务一段时间

**Comment by ametoyuki098** [comment]
打不开了

**Comment by greensea** [comment]
> 今天会更换一下磁盘阵列服务器的系统盘，还会暂停服务一段时间

今日维护已结束，未来一段时间可能还会有小维护，届时可能还会短时停机

**Comment by whitecodes** [comment]
确认可以正常使用了
